# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(892, 554)
        MainWindow.setMinimumSize(QtCore.QSize(500, 425))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 756))
        MainWindow.setFocusPolicy(QtCore.Qt.ClickFocus)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.img_lbl = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.img_lbl.sizePolicy().hasHeightForWidth())
        self.img_lbl.setSizePolicy(sizePolicy)
        self.img_lbl.setAutoFillBackground(False)
        self.img_lbl.setText(_fromUtf8(""))
        self.img_lbl.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/init.png")))
        self.img_lbl.setScaledContents(True)
        self.img_lbl.setObjectName(_fromUtf8("img_lbl"))
        self.verticalLayout.addWidget(self.img_lbl)
        self.lbl_ImgName = QtGui.QLabel(self.centralwidget)
        self.lbl_ImgName.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_ImgName.setObjectName(_fromUtf8("lbl_ImgName"))
        self.verticalLayout.addWidget(self.lbl_ImgName)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_7)
        self.minW_lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.minW_lineEdit.setMaximumSize(QtCore.QSize(90, 16777215))
        self.minW_lineEdit.setObjectName(_fromUtf8("minW_lineEdit"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.minW_lineEdit)
        self.label_8 = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_8)
        self.minH_lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.minH_lineEdit.setMaximumSize(QtCore.QSize(90, 16777215))
        self.minH_lineEdit.setObjectName(_fromUtf8("minH_lineEdit"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.minH_lineEdit)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label)
        self.prob_lineEdit = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prob_lineEdit.sizePolicy().hasHeightForWidth())
        self.prob_lineEdit.setSizePolicy(sizePolicy)
        self.prob_lineEdit.setMaximumSize(QtCore.QSize(90, 16777215))
        self.prob_lineEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.prob_lineEdit.setObjectName(_fromUtf8("prob_lineEdit"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.prob_lineEdit)
        self.checkB_Reverse = QtGui.QCheckBox(self.centralwidget)
        self.checkB_Reverse.setObjectName(_fromUtf8("checkB_Reverse"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.checkB_Reverse)
        self.horizontalLayout_3.addLayout(self.formLayout)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.cmComboBox = QtGui.QComboBox(self.centralwidget)
        self.cmComboBox.setMaximumSize(QtCore.QSize(90, 16777215))
        self.cmComboBox.setObjectName(_fromUtf8("cmComboBox"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.cmComboBox)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.mode_comboBox = QtGui.QComboBox(self.centralwidget)
        self.mode_comboBox.setMaximumSize(QtCore.QSize(90, 16777215))
        self.mode_comboBox.setObjectName(_fromUtf8("mode_comboBox"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.mode_comboBox)
        self.clusterProb_RadioBtn = QtGui.QCheckBox(self.centralwidget)
        self.clusterProb_RadioBtn.setObjectName(_fromUtf8("clusterProb_RadioBtn"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.clusterProb_RadioBtn)
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_9)
        self.cbox_ClassIndex = QtGui.QComboBox(self.centralwidget)
        self.cbox_ClassIndex.setObjectName(_fromUtf8("cbox_ClassIndex"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.cbox_ClassIndex)
        self.horizontalLayout_3.addLayout(self.formLayout_4)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.eps_spinBox = QtGui.QSpinBox(self.centralwidget)
        self.eps_spinBox.setEnabled(False)
        self.eps_spinBox.setMaximumSize(QtCore.QSize(90, 16777215))
        self.eps_spinBox.setObjectName(_fromUtf8("eps_spinBox"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.eps_spinBox)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.minPoints_spinBox = QtGui.QSpinBox(self.centralwidget)
        self.minPoints_spinBox.setEnabled(False)
        self.minPoints_spinBox.setMaximumSize(QtCore.QSize(90, 16777215))
        self.minPoints_spinBox.setObjectName(_fromUtf8("minPoints_spinBox"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.minPoints_spinBox)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_6)
        self.dbscanGroupBy_comboBox = QtGui.QComboBox(self.centralwidget)
        self.dbscanGroupBy_comboBox.setEnabled(False)
        self.dbscanGroupBy_comboBox.setMaximumSize(QtCore.QSize(90, 16777215))
        self.dbscanGroupBy_comboBox.setObjectName(_fromUtf8("dbscanGroupBy_comboBox"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.dbscanGroupBy_comboBox)
        self.horizontalLayout_3.addLayout(self.formLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 892, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuEdit = QtGui.QMenu(self.menubar)
        self.menuEdit.setObjectName(_fromUtf8("menuEdit"))
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setMovable(True)
        self.toolBar.setAllowedAreas(QtCore.Qt.AllToolBarAreas)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.LeftToolBarArea, self.toolBar)
        self.actionLoad = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/load.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLoad.setIcon(icon)
        self.actionLoad.setObjectName(_fromUtf8("actionLoad"))
        self.actionEraser = QtGui.QAction(MainWindow)
        self.actionEraser.setEnabled(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/eraser.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEraser.setIcon(icon1)
        self.actionEraser.setObjectName(_fromUtf8("actionEraser"))
        self.actionNext_Image = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/next.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNext_Image.setIcon(icon2)
        self.actionNext_Image.setObjectName(_fromUtf8("actionNext_Image"))
        self.actionPrevious_Image = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/previous.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPrevious_Image.setIcon(icon3)
        self.actionPrevious_Image.setObjectName(_fromUtf8("actionPrevious_Image"))
        self.actionUndo = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/undo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUndo.setIcon(icon4)
        self.actionUndo.setObjectName(_fromUtf8("actionUndo"))
        self.actionMake_video = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/video.jpeg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMake_video.setIcon(icon5)
        self.actionMake_video.setObjectName(_fromUtf8("actionMake_video"))
        self.menuFile.addAction(self.actionLoad)
        self.menuEdit.addAction(self.actionNext_Image)
        self.menuEdit.addAction(self.actionPrevious_Image)
        self.menuEdit.addAction(self.actionMake_video)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.toolBar.addAction(self.actionLoad)
        self.toolBar.addAction(self.actionNext_Image)
        self.toolBar.addAction(self.actionPrevious_Image)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionMake_video)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Watching Prob Events", None))
        self.lbl_ImgName.setText(_translate("MainWindow", "img name", None))
        self.label_7.setText(_translate("MainWindow", "Min width", None))
        self.label_8.setText(_translate("MainWindow", "Min Height", None))
        self.label.setText(_translate("MainWindow", "Filter probability", None))
        self.prob_lineEdit.setPlaceholderText(_translate("MainWindow", "prob number...", None))
        self.checkB_Reverse.setText(_translate("MainWindow", "Rotate Image", None))
        self.label_2.setText(_translate("MainWindow", "Select Color Map", None))
        self.label_5.setText(_translate("MainWindow", "Mode", None))
        self.clusterProb_RadioBtn.setText(_translate("MainWindow", "Use cluster prob", None))
        self.label_9.setText(_translate("MainWindow", "Class index", None))
        self.label_3.setText(_translate("MainWindow", "DBSCAN epsilon", None))
        self.label_4.setText(_translate("MainWindow", "DBSCAN min points", None))
        self.label_6.setText(_translate("MainWindow", "DBSCAN group by", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionLoad.setText(_translate("MainWindow", "Load file...", None))
        self.actionLoad.setShortcut(_translate("MainWindow", "Ctrl+L", None))
        self.actionEraser.setText(_translate("MainWindow", "Eraser", None))
        self.actionEraser.setToolTip(_translate("MainWindow", "Erase events from image", None))
        self.actionNext_Image.setText(_translate("MainWindow", "Next Image", None))
        self.actionNext_Image.setShortcut(_translate("MainWindow", "Right", None))
        self.actionPrevious_Image.setText(_translate("MainWindow", "Previous Image", None))
        self.actionPrevious_Image.setShortcut(_translate("MainWindow", "Left", None))
        self.actionUndo.setText(_translate("MainWindow", "Undo", None))
        self.actionUndo.setShortcut(_translate("MainWindow", "Ctrl+Z", None))
        self.actionMake_video.setText(_translate("MainWindow", "Make video", None))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

